[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "php82Extensions.pdo_pgsql", "php82Extensions.gd", "php82Extensions.bcmath", "php82Extensions.zip", "php82Extensions.intl", "php82Extensions.mbstring", "php82Extensions.xml", "php82Extensions.curl", "nodejs", "yarn"]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader --ignore-platform-reqs",
    "php artisan optimize:clear",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
cmd = "php artisan migrate --force && php artisan db:seed --force && php artisan storage:link && php artisan serve --host=0.0.0.0 --port=$PORT"
