web: php artisan migrate --force && php artisan db:seed --force && php artisan storage:link && php artisan serve --host=0.0.0.0 --port=$PORT
release: composer install --no-dev --optimize-autoloader --ignore-platform-reqs
