web: php artisan config:clear && php artisan cache:clear && php artisan migrate --force && php artisan db:seed --class=SettingSeeder --force && php artisan storage:link && php artisan serve --host=0.0.0.0 --port=$PORT
release: composer install --no-dev --optimize-autoloader --ignore-platform-reqs
